# This is a basic workflow to help you get started with Actions

name: Update list

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_list:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Update list
        run: |
          curl -s https://antifilter.network/download/ipsmart.lst | sed -e 's/^/IP-CIDR,/' > ipsmart.list
          curl -s https://antifilter.network/download/ip6.lst | sed -e 's/^/IP-CIDR6,/' >> ip6.list
          git config --global user.name 'DemonFromRussia'
          git config --global user.email 'demonfromrussia@users.noreply.github.com'
          git add *
          git commit --amend -m "Update list $(date '+%Y-%m-%d %H:%M:%S')"
          git push --force
